services:
  db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: campolog_db
      POSTGRES_USER: campolog
      POSTGRES_PASSWORD: campolog123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: campolog_db
      DB_USER: campolog
      DB_PASSWORD: campolog123
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - static_files:/app/staticfiles
      - media_files:/app/media

volumes:
  pgdata:
  static_files:
  media_files:
