# Generated by Django 6.0.5 on 2026-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('ATIVO', 'Ativo / Em andamento'), ('COLHIDO', 'Colhido / Finalizado'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('variedade', models.CharField(blank=True, help_text='Ex: Verdão, Crioulo', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.TextField(blank=True, help_text='Coordenadas GPS do polígono', null=True)),
                ('nome', models.CharField(max_length=100)),
                ('area_m2', models.FloatField()),
            ],
        ),
    ]
