# Generated by Django 5.1.7 on 2026-04-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('variedade', models.CharField(blank=True, help_text='Ex: Verdão, Crioulo', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Setor A - Parcela 04', max_length=100)),
                ('area_m2', models.DecimalField(decimal_places=2, help_text='Área em metros quadrados', max_digits=10)),
                ('coordenadas', models.TextField(blank=True, help_text='Coordenadas GPS do polígono', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CicloCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('ATIVO', 'Ativo / Em andamento'), ('COLHIDO', 'Colhido / Finalizado'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='agronomia.cultura')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='agronomia.talhao')),
            ],
        ),
    ]
