# Generated by Django 6.0.5 on 2026-05-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agronomia', '0001_initial'),
        ('caderno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclocultivo',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='caderno.unidadeprodutiva'),
        ),
        migrations.AddField(
            model_name='ciclocultivo',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='culturas', to='agronomia.cultura'),
        ),
        migrations.AddField(
            model_name='talhao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='caderno.unidadeprodutiva'),
        ),
        migrations.AddField(
            model_name='ciclocultivo',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agronomia.talhao'),
        ),
    ]
