# Generated by Django 6.0.5 on 2026-05-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclocultivo',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='agronomia.cultura'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='area_m2',
            field=models.FloatField(help_text='Área em metros quadrados'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='nome',
            field=models.CharField(help_text='Ex: Setor A - Parcela 04', max_length=100),
        ),
    ]
