# Generated by Django 6.0.5 on 2026-05-16 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agronomia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeProdutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Campus Petrolina, Fazenda Experimental', max_length=150)),
                ('cnpj_ou_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(related_name='unidades_acessiveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('REGA', 'Rega / Irrigação'), ('INSUMO', 'Aplicação de Insumo / Adubo'), ('OBSERVACAO', 'Observação (Pragas, Doenças, Fenologia)'), ('COLHEITA', 'Colheita'), ('OUTRO', 'Outra Operação')], max_length=20)),
                ('descricao', models.TextField(help_text='Detalhes da atividade, produto utilizado ou observação visual.')),
                ('quantidade', models.CharField(blank=True, help_text='Ex: 2 Litros de calda, 10kg colhidos', max_length=100, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='diario/%Y/%m/%d/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meus_registos', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agronomia.ciclocultivo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='caderno.unidadeprodutiva')),
            ],
            options={
                'ordering': ['-data_registo'],
            },
        ),
    ]
