# Generated by Django 5.1.7 on 2026-04-18 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agronomia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('REGA', 'Rega / Irrigação'), ('INSUMO', 'Aplicação de Insumo / Adubo'), ('OBSERVACAO', 'Observação (Pragas, Doenças, Fenologia)'), ('COLHEITA', 'Colheita'), ('OUTRO', 'Outra Operação')], max_length=20)),
                ('descricao', models.TextField(help_text='Detalhes da atividade, produto utilizado ou observação visual.')),
                ('quantidade', models.CharField(blank=True, help_text='Ex: 2 Litros de calda, 10kg colhidos', max_length=100, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meus_registos', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_campo', to='agronomia.ciclocultivo')),
            ],
            options={
                'ordering': ['-data_registo'],
            },
        ),
    ]
