# Generated by Django 5.1.7 on 2026-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registocampo',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='diario/%Y/%m/%d/'),
        ),
    ]
