# Generated by Django 6.0.5 on 2026-05-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomia', '0003_refactor_related_names'),
        ('caderno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registocampo',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_campo', to='agronomia.ciclocultivo'),
        ),
    ]
