# Generated by Django 6.0.5 on 2026-06-18 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caderno', '0002_refactor_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, help_text='Snapshot do nome do utilizador no momento da ação.', max_length=150)),
                ('acao', models.CharField(choices=[('CRIAR', 'Criação'), ('ATUALIZAR', 'Atualização'), ('EXCLUIR', 'Exclusão')], max_length=20)),
                ('entidade', models.CharField(help_text='Nome do model afetado, ex.: RegistoCampo', max_length=100)),
                ('entidade_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='caderno.unidadeprodutiva')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
